language: go
go: '1.13'
os:
- osx
arch:
- amd64
osx_image: xcode11.3
before_script:
- APP_VER=$(git describe --tags --long --dirty)
- APP_VER_SHORT=$(git describe --tags)
- GOOS=$(go env GOOS)
- GOARCH=$(go env GOARCH)
- ARCHIVE="elrond_""$APP_VER_SHORT""_""$GOOS""_""$GOARCH"".tgz"
script:
- go build -o "$TRAVIS_BUILD_DIR/build/arwen" -a -i -ldflags="-X main.appVersion=$APP_VER"
- go build -o "$TRAVIS_BUILD_DIR/build/arwendebug" -a -i -ldflags="-X main.appVersion=$APP_VER"
- go build -o "$TRAVIS_BUILD_DIR/build/test" -a -i -ldflags="-X main.appVersion=$APP_VER"
- otool -L $TRAVIS_BUILD_DIR/wasmer/libwasmer_darwin_amd64.dylib
- install_name_tool -id $TRAVIS_BUILD_DIR/wasmer/libwasmer_darwin_amd64.dylib $TRAVIS_BUILD_DIR/wasmer/libwasmer_darwin_amd64.dylib
- GOOS=$(go env GOOS)
- GOARCH=$(go env GOARCH)

- if [[ "$GOOS" == linux && "$GOARCH" == amd64 ]]; then cp -f $TRAVIS_BUILD_DIR/wasmer/libwasmer_linux_amd64.so
  $TRAVIS_BUILD_DIR/build; fi
- if [[ "$GOOS" == darwin && "$GOARCH" == amd64 ]]; then cp -f $TRAVIS_BUILD_DIR/wasmer/libwasmer_darwin_amd64.dylib
  $TRAVIS_BUILD_DIR/build; fi
- make test-short
before_deploy:
- cd "$TRAVIS_BUILD_DIR/build"
- tar czvf "$TRAVIS_BUILD_DIR/$ARCHIVE" *
after_deploy:
- rm -rf "$TRAVIS_BUILD_DIR/build"
- rm -rf "$TRAVIS_BUILD_DIR/$ARCHIVE"
deploy:
  provider: s3
  access_key_id:
    secure: In58U7u1IXtDpm6BbR2NSUHKgz+VYBVmqP3vLrUQZykUYXt1WVL3EGcM5hMdQQHawXa+2YQ494R3E35H0RvHXxQTwZurfyVCCYbBCWa/LYBDITlQlA5SAi7zVyI/mVTc4P52i2CNYmR+Y03Ry+Bn3DdiGXGHsoD/LAUQy0ZNiNpp74OQ3q/P6q0tcxoVjtlJ2q38FOU8AVYul65RNyJjAeHfi0Y7dn+rJF2ZByR2q1WJr922eW50lWj5LaGokPoNEocHGA+RyaCOTyY/OFO2R2k0/6FVcW499I3Ic7qShlaBpXjordtKahkf5M0ACR93uYOrjPYeR5cf2CoJr8AyQpg2WcO6+ZDcP8Li7E90GLDEaRkONDL1ZXQ8Qe4nZqhVwaz6quREbCLK+d/33z/5Iwnp9SiG+txWSWlafWoE/BEKGDf46Eq2XMUAkQt4LqBRUR+Sqg1VVCkrqbfUmfu9HYvehhmaGaUKi04bJdLdCvwNzo1d4OsajfN+rEIIiUog6McEZtpFv/VkUG/i4zDKOu68uKc+2JKQ6pe39AenyFrt9eMQ7uIkfFfBhhtshbDGWIX8wVXGwIwMuFJ0cwiFbwqy+eoJdKAXV0/+H2OSgFNFEn9PvYbYs3JD1ZgBHwMyeJkeJWxeNzI/74BOIFN66eLbtP5uwwe7ykLelenSzus=
  secret_access_key:
    secure: Bbe71JHeIa256ffMOMgckgjxAb1TX4Vy3T+WfFB5Q7uaZNhr6wk2WzE46xfWPNNFcjKMyy46W18cTDQWHSLNhO7dGhelTysU5TSeezQ9V5y9FssKjkh4L4DR7FGy4iojzuUOXea3tP/ttlQwjlfoSV+yP5CZXbVbpWRuN++3mS51uC4IU2rmvwjym7nNVuSbIuHW8QtnTCiWjnWBqFhE5Mc4lmt5bVcX5HAhGGpFk+d42lgdYIUzArCyevUI/+/wHBmMrcfju0fKCfOFM4wdMkVKvyvwtkwz5OgkPh+THTv9h7dmRupsbZZ+iv4WgyAHJ9R18hP6Mr+uhJRlLLb3+j+6wtWJ+yj7RB9MZJzy96KQ1e51k74rXqaVJnV7DeEluQUghryDq5y04s4hqfFvS4vs/XsUVOL3MSDcKPT44n1Ku4eBrmpq403dPm15B6X3rJMFStr/bWO2s52gZ0OAKi/RGbcPTZcQ8Q4o48VjpMOxXLXsTLNMYHemM4H0jLY0FEDajBbV8AIuPwsG6GQceif099T0MYLIrOm+jbW9gbfmGvG2Bnhj/HX2TkGUQayTIBBBhFPFsKHTBIrt8Wa538+ljB/+Oab0jRCzVtqYZDPqQ1/zkq1vthcVhuRyoFfoVZSA5b6yDV6fo9UyOH2eNLW9Xn9bAGHd64WBq0EnRcI=
  bucket: ide.elrond.com
  skip_cleanup: true
  glob: "$ARCHIVE"
  branches:
    only:
    - master
    - arwendebug

